[package]
name = "seven-sketches"
version = "0.1.0"
authors = ["Ben Pski <ben@pepski.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[[bin]]
name = "sketches"
path = "src/main.rs"

[dependencies]
rocket = "0.5.0"

[dev-dependencies]

